version: "3.7"

services:
  web:
    image: vincenteat/utorrent:latest
    container_name: utorrent
    ports:
      - "8082:8080"
    volumes:
      - ./autoload:/var/utorrent/autoload
      - ./completed:/var/utorrent/completed
      - ./settings:/var/log/utorrent
