version: "3.7"

services:
  web:
    image: vincenteat/utorrent:latest
    container_name: utorrent
    ports:
      - "8082:8080"
    volumes:
      - /home/vincenzo/Torrent/autoload:/var/utorrent/autoload
      - /home/vincenzo/Torrent/completed:/var/torrent/completed
      - /home/vincenzo/Torrent/conf/settings.dat:/opt/utorrent-server-alpha-v3_3/settings.dat
