name: Build the Docker image

on:
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - 
        name: Build
        run: docker build . --file Dockerfile --tag utorrent:$(date +%s)
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  